### ISSUE TITLE
Can't get URL, because route is failed to parse

### ISSUE THREAD

**Issue by adipriyantobpn** [sergeymakinen/yii2-log-message#2]
In my case, I activate `enablePrettyUrl`, `showScriptName`, and `enableStrictParsing` properties in **urlManager** component.

Then when I try to put random string in the URL, Message::getUrl() returns error because `yii\helpers\Url::current()` can't parse the route.

**Comment by adipriyantobpn** [comment]
Below is the stack trace from the error.

![error from url-current](https://user-images.githubusercontent.com/4537439/29421670-ffaf29f2-839f-11e7-82c8-8499e656f6ed.png)

**Comment by sergeymakinen** [comment]
There's now [2.0.1](https://github.com/sergeymakinen/yii2-log-message/releases/tag/v2.0.1) with this bug fixed. Thanks! ✌️

**Comment by adipriyantobpn** [comment]
whoahh.. thank you so much for your super fast response..
