### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by vuylov** [sergeymakinen/yii2-log-message#4]
Hi, thx for job.
https://github.com/sergeymakinen/yii2-log-message/blob/master/src/Message.php#L35

Deprecated useage class Object

Need: https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

**Comment by sergeymakinen** [comment]
Sorry for the long delay - I was extremely busy at work. :( I'll review it on this weekend.
